### ISSUE TITLE
Fail to load pth model files

### ISSUE THREAD

**Issue by ReedZyd** [siriusdemon/pytorch-DEX#1]
I have encountered a problem：
Traceback (most recent call last):
  File "demo.py", line 5, in <module>
    dex.eval()
  File "/home/zyd/Reed/DL/age-estimation/code/pytorch-DEX/dex/api.py", line 23, in _eval
    gender_model.load_state_dict(torch.load(gender_model_path))
  File "/home/zyd/anaconda3/envs/pytorch/lib/python3.5/site-packages/torch/serialization.py", line 367, in load
    return _load(f, map_location, pickle_module)
  File "/home/zyd/anaconda3/envs/pytorch/lib/python3.5/site-packages/torch/serialization.py", line 528, in _load
    magic_number = pickle_module.load(f)
_pickle.UnpicklingError: invalid load key, 'v'.

How can I solve it?

**Comment by siriusdemon** [comment]
![image](https://user-images.githubusercontent.com/14900195/54585142-4eb98480-4a54-11e9-8bf8-c70849337bdc.png)

You should first install [git-lfs](https://git-lfs.github.com/), because its pth files are stored in remote lfs server.

**Comment by ReedZyd** [comment]
The problem still exists and I can't download dex/pth/age_sd.pth(539 MB).

**Comment by siriusdemon** [comment]
Maybe you can download here and replace the two git-lfs pointer file in dex/dex/pth.
[gender_sd.pth](https://drive.google.com/file/d/1ancMcq5b_0nppdIAav1UgBxdiaMnnQPe/view)
[age_sd.pth](https://drive.google.com/file/d/1KtzJBcGPMwjYdxbJkfEeRFzxNMaTVykH/view)

**Comment by ReedZyd** [comment]
I solved this problem by installing git-lfs with apt-get. Also, is there code that tests performance?I want to test the DEX network by MAE.

**Comment by ReedZyd** [comment]
> Maybe you can download here and replace the two git-lfs pointer file in dex/dex/pth.
> [gender_sd.pth](https://drive.google.com/file/d/1ancMcq5b_0nppdIAav1UgBxdiaMnnQPe/view)
> [age_sd.pth](https://drive.google.com/file/d/1KtzJBcGPMwjYdxbJkfEeRFzxNMaTVykH/view)

Thank you very much!

**Comment by siriusdemon** [comment]
> I solved this problem by installing git-lfs with apt-get. Also, is there code that tests performance?I want to test the DEX network by MAE.

You can have a try! Refer to its [home page](https://data.vision.ee.ethz.ch/cvl/rrothe/imdb-wiki/) for performance metrics.

**Comment by ReedZyd** [comment]
I still have a problem with downloading model...It seams to wait too long time and failed.

**Comment by ReedZyd** [comment]
[图片]

**Comment by ReedZyd** [comment]
![YUXWT_7EQ7JJNCY `4 HES](https://user-images.githubusercontent.com/48706305/54590556-55032d00-4a63-11e9-8db0-794d9a1adb47.png)

**Comment by siriusdemon** [comment]
The Great Firewall ... ... It seems that it is not a good idea to store large file by git-lfs.
Download from Google Drive or Baiduwangpang:
link: https://pan.baidu.com/s/1pnU7ZwzYU4MqCvRQN6xN0Q 
code: vdij

**Comment by ReedZyd** [comment]
Yes,I solve it!

**Comment by neverUseThisName** [comment]
> Maybe you can download here and replace the two git-lfs pointer file in dex/dex/pth.
> [gender_sd.pth](https://drive.google.com/file/d/1ancMcq5b_0nppdIAav1UgBxdiaMnnQPe/view)
> [age_sd.pth](https://drive.google.com/file/d/1KtzJBcGPMwjYdxbJkfEeRFzxNMaTVykH/view)

how to modify .pth file after downloading the models?

**Comment by siriusdemon** [comment]
If any git-lfs pointer exists in `dex/dex/pth`, remove them.
Once you have downloaded this two files, move them to `dex/dex/pth`.

**Comment by danilocoura** [comment]
> Maybe you can download here and replace the two git-lfs pointer file in dex/dex/pth.
> [gender_sd.pth](https://drive.google.com/file/d/1ancMcq5b_0nppdIAav1UgBxdiaMnnQPe/view)
> [age_sd.pth](https://drive.google.com/file/d/1KtzJBcGPMwjYdxbJkfEeRFzxNMaTVykH/view)

Hi. Do you have the pytorch models only trained with the imdb-wiki datasets? (I think these are also trained with the chalearn database) 

Thank you!

**Comment by siriusdemon** [comment]
No. But there are other DEX implementations on github, Good luck! Happy New Year!

**Comment by danilocoura** [comment]
Hi, Sirius.

Thanks for your answer.
Happy New Year!

I am stuck in this problem. You released the pytorch model of
"dex_chalearn_iccv2015.caffemodel". I tried to use your code (convert.py)
to convert the "dex_imdb_wiki.caffemodel" (
https://data.vision.ee.ethz.ch/cvl/rrothe/imdb-wiki/static/dex_imdb_wiki.caffemodel),
but I am having problems with the protobuf size. I would like to know how
you deal with this or if you could convert this model to me, please.

I really appreciate your help.

best regards

Danilo

**Comment by danilocoura** [comment]
Hi, Sirius.

I've managed my issue. I used the MMDNN to convert the models (caffe to
pytorch). So, disregard the last e-mail.

Thanks for your attention.

best regards,

Danilo

**Comment by quocnhat** [comment]
> Maybe you can download here and replace the two git-lfs pointer file in dex/dex/pth.
> [gender_sd.pth](https://drive.google.com/file/d/1ancMcq5b_0nppdIAav1UgBxdiaMnnQPe/view)
> [age_sd.pth](https://drive.google.com/file/d/1KtzJBcGPMwjYdxbJkfEeRFzxNMaTVykH/view)

solved the problem by either git-lfs installing and replacing 2 pretrained files. thanks
